# supports version 2 of the docker compose language. 
# Requires docker compose 1.6 or later
version: '2'

services:
  node:
    container_name: node
    build: 
      context: .
      dockerfile: Dockerfile-node
    ports:
     - "8000:8000"
    links:
     - "mongo:mongo"
    depends_on:
     - mongo
  mongo:
    build: 
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongo

     
